import Sidebar from '@/components/Sidebar'
import Feed from '@/components/Feed'
import Head from 'next/head'



export default function Home() {
  return (
    <div>
      <Head>
        <title>TwitterClone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* basically the maintag(a semantic tag) is used to show the main content of your site and also good for seo  */}
      <main className="flex min-h-screen max-w-7xl mx-auto "> 

        {/* sidebar */}

        <Sidebar />


        {/* feed */}

        <Feed />

        {/* widget  */}

        {/* modal --pops up  */}

      </main>
    </div>



  )
}
